# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-05 22:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ataque', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ataque',
            name='potencia',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='ataque',
            name='precision',
            field=models.IntegerField(default=10),
        ),
    ]
