# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-04 23:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entrenador', '0001_initial'),
        ('pokemon', '0002_auto_20160821_2200'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pokedex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiporegistro', models.CharField(choices=[('Visto', 'Visto'), ('Capturado', 'Capturado')], max_length=9)),
                ('entrenador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrenador.Entrenador')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon.Pokemon')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='pokedex',
            unique_together=set([('pokemon', 'entrenador')]),
        ),
    ]
