# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-04 23:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entrenador', '0002_auto_20161004_1858'),
        ('pokemon', '0002_auto_20160821_2200'),
        ('pokedex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokedex',
            name='entrenador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokedex_entrenador', to='entrenador.Entrenador'),
        ),
        migrations.AlterField(
            model_name='pokedex',
            name='pokemon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokedex_pokemon', to='pokemon.Pokemon'),
        ),
        migrations.AlterUniqueTogether(
            name='pokedex',
            unique_together=set([('entrenador', 'pokemon')]),
        ),
    ]
