# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-22 01:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pokemon', '0002_auto_20160821_2200'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrenador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('nivel', models.IntegerField(default=1)),
                ('equipo', models.CharField(choices=[('Mystic', 'Mystic'), ('Valor', 'Valor'), ('instinct', 'instinct')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='EntrenadorHasPokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('cp', models.IntegerField(default=1)),
                ('hp', models.IntegerField(default=1)),
                ('entrenador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrenador.Entrenador')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon.Pokemon')),
            ],
        ),
        migrations.AddField(
            model_name='entrenador',
            name='pokemones',
            field=models.ManyToManyField(through='entrenador.EntrenadorHasPokemon', to='pokemon.Pokemon'),
        ),
    ]
