# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-12 02:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0003_ataque'),
        ('entrenador', '0002_auto_20161004_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrenadorhaspokemon',
            name='ataques',
            field=models.ManyToManyField(to='pokemon.Ataque'),
        ),
    ]
