# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-05 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0002_auto_20160821_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipopokemon',
            name='nombre',
            field=models.CharField(choices=[('Agua', 'Agua'), ('Fuego', 'Fuego'), ('Planta', 'Planta')], max_length=50),
        ),
    ]
