# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-12 01:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0002_auto_20160821_2200'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ataque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('poder', models.IntegerField()),
                ('punteria', models.IntegerField()),
                ('tipo_pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ataque_tipo', to='pokemon.TipoPokemon')),
            ],
        ),
    ]
