# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-05 22:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0003_auto_20161005_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='tipo',
            field=models.ForeignKey(choices=[('Agua', 'Agua'), ('Fuego', 'Fuego'), ('Planta', 'Planta')], on_delete=django.db.models.deletion.CASCADE, to='pokemon.TipoPokemon'),
        ),
    ]
