# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-05 23:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ataque', '0002_auto_20161005_1745'),
        ('pokemon', '0007_auto_20161005_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='PokemonHasAtaque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ataque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ataque_has_pokemon_pokemon', to='ataque.Ataque')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokemon_has_ataque_pokemon', to='pokemon.Pokemon')),
            ],
        ),
        migrations.AddField(
            model_name='pokemon',
            name='ataques',
            field=models.ManyToManyField(related_name='pokemon_has_ataque', through='pokemon.PokemonHasAtaque', to='ataque.Ataque'),
        ),
    ]
